// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/player.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiPlayerInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => 771177210;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'gst_audio_core',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<PlaybackState> crateApiPlayerFadeIn({
    required PlatformInt64 durationMs,
  });

  Future<PlaybackState> crateApiPlayerFadeOut({
    required PlatformInt64 durationMs,
  });

  Future<PlaybackState> crateApiPlayerGetState();

  Future<void> crateApiPlayerInitApp();

  Future<List<AudioOutputDevice>> crateApiPlayerListOutputDevices();

  Future<PlaybackState> crateApiPlayerNext();

  Future<PlaybackState> crateApiPlayerPause();

  Future<PlaybackState> crateApiPlayerPlay();

  Future<PlaybackState> crateApiPlayerPlayIndex({required int index});

  Future<PlaybackState> crateApiPlayerPrevious();

  Future<PlaybackState> crateApiPlayerSeekMs({
    required PlatformInt64 positionMs,
  });

  Future<PlaybackState> crateApiPlayerSetMuted({required bool muted});

  Future<PlaybackState> crateApiPlayerSetOutputDevice({
    required String deviceId,
  });

  Future<PlaybackState> crateApiPlayerSetPlaylist({
    required List<String> inputs,
    required int startIndex,
  });

  Future<PlaybackState> crateApiPlayerSetRepeatMode({required RepeatMode mode});

  Future<PlaybackState> crateApiPlayerSetShuffle({required bool enabled});

  Future<PlaybackState> crateApiPlayerSetSpeed({required double speed});

  Future<PlaybackState> crateApiPlayerSetVolume({required double volume});

  Future<void> crateApiPlayerShutdownPlayer();

  Future<PlaybackState> crateApiPlayerStop();

  Future<PlaybackState> crateApiPlayerTogglePlayPause();
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<PlaybackState> crateApiPlayerFadeIn({
    required PlatformInt64 durationMs,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(durationMs, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_playback_state,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiPlayerFadeInConstMeta,
        argValues: [durationMs],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPlayerFadeInConstMeta =>
      const TaskConstMeta(debugName: "fade_in", argNames: ["durationMs"]);

  @override
  Future<PlaybackState> crateApiPlayerFadeOut({
    required PlatformInt64 durationMs,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(durationMs, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_playback_state,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiPlayerFadeOutConstMeta,
        argValues: [durationMs],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPlayerFadeOutConstMeta =>
      const TaskConstMeta(debugName: "fade_out", argNames: ["durationMs"]);

  @override
  Future<PlaybackState> crateApiPlayerGetState() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_playback_state,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiPlayerGetStateConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPlayerGetStateConstMeta =>
      const TaskConstMeta(debugName: "get_state", argNames: []);

  @override
  Future<void> crateApiPlayerInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiPlayerInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPlayerInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<List<AudioOutputDevice>> crateApiPlayerListOutputDevices() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_audio_output_device,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiPlayerListOutputDevicesConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPlayerListOutputDevicesConstMeta =>
      const TaskConstMeta(debugName: "list_output_devices", argNames: []);

  @override
  Future<PlaybackState> crateApiPlayerNext() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_playback_state,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiPlayerNextConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPlayerNextConstMeta =>
      const TaskConstMeta(debugName: "next", argNames: []);

  @override
  Future<PlaybackState> crateApiPlayerPause() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_playback_state,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiPlayerPauseConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPlayerPauseConstMeta =>
      const TaskConstMeta(debugName: "pause", argNames: []);

  @override
  Future<PlaybackState> crateApiPlayerPlay() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_playback_state,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiPlayerPlayConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPlayerPlayConstMeta =>
      const TaskConstMeta(debugName: "play", argNames: []);

  @override
  Future<PlaybackState> crateApiPlayerPlayIndex({required int index}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_32(index, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_playback_state,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiPlayerPlayIndexConstMeta,
        argValues: [index],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPlayerPlayIndexConstMeta =>
      const TaskConstMeta(debugName: "play_index", argNames: ["index"]);

  @override
  Future<PlaybackState> crateApiPlayerPrevious() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_playback_state,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiPlayerPreviousConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPlayerPreviousConstMeta =>
      const TaskConstMeta(debugName: "previous", argNames: []);

  @override
  Future<PlaybackState> crateApiPlayerSeekMs({
    required PlatformInt64 positionMs,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(positionMs, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_playback_state,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiPlayerSeekMsConstMeta,
        argValues: [positionMs],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPlayerSeekMsConstMeta =>
      const TaskConstMeta(debugName: "seek_ms", argNames: ["positionMs"]);

  @override
  Future<PlaybackState> crateApiPlayerSetMuted({required bool muted}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_bool(muted, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_playback_state,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiPlayerSetMutedConstMeta,
        argValues: [muted],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPlayerSetMutedConstMeta =>
      const TaskConstMeta(debugName: "set_muted", argNames: ["muted"]);

  @override
  Future<PlaybackState> crateApiPlayerSetOutputDevice({
    required String deviceId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(deviceId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_playback_state,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiPlayerSetOutputDeviceConstMeta,
        argValues: [deviceId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPlayerSetOutputDeviceConstMeta =>
      const TaskConstMeta(
        debugName: "set_output_device",
        argNames: ["deviceId"],
      );

  @override
  Future<PlaybackState> crateApiPlayerSetPlaylist({
    required List<String> inputs,
    required int startIndex,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_String(inputs, serializer);
          sse_encode_i_32(startIndex, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_playback_state,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiPlayerSetPlaylistConstMeta,
        argValues: [inputs, startIndex],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPlayerSetPlaylistConstMeta => const TaskConstMeta(
    debugName: "set_playlist",
    argNames: ["inputs", "startIndex"],
  );

  @override
  Future<PlaybackState> crateApiPlayerSetRepeatMode({
    required RepeatMode mode,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_repeat_mode(mode, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_playback_state,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiPlayerSetRepeatModeConstMeta,
        argValues: [mode],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPlayerSetRepeatModeConstMeta =>
      const TaskConstMeta(debugName: "set_repeat_mode", argNames: ["mode"]);

  @override
  Future<PlaybackState> crateApiPlayerSetShuffle({required bool enabled}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_bool(enabled, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_playback_state,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiPlayerSetShuffleConstMeta,
        argValues: [enabled],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPlayerSetShuffleConstMeta =>
      const TaskConstMeta(debugName: "set_shuffle", argNames: ["enabled"]);

  @override
  Future<PlaybackState> crateApiPlayerSetSpeed({required double speed}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_f_64(speed, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_playback_state,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiPlayerSetSpeedConstMeta,
        argValues: [speed],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPlayerSetSpeedConstMeta =>
      const TaskConstMeta(debugName: "set_speed", argNames: ["speed"]);

  @override
  Future<PlaybackState> crateApiPlayerSetVolume({required double volume}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_f_64(volume, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 18,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_playback_state,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiPlayerSetVolumeConstMeta,
        argValues: [volume],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPlayerSetVolumeConstMeta =>
      const TaskConstMeta(debugName: "set_volume", argNames: ["volume"]);

  @override
  Future<void> crateApiPlayerShutdownPlayer() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 19,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiPlayerShutdownPlayerConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPlayerShutdownPlayerConstMeta =>
      const TaskConstMeta(debugName: "shutdown_player", argNames: []);

  @override
  Future<PlaybackState> crateApiPlayerStop() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 20,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_playback_state,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiPlayerStopConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPlayerStopConstMeta =>
      const TaskConstMeta(debugName: "stop", argNames: []);

  @override
  Future<PlaybackState> crateApiPlayerTogglePlayPause() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 21,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_playback_state,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiPlayerTogglePlayPauseConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPlayerTogglePlayPauseConstMeta =>
      const TaskConstMeta(debugName: "toggle_play_pause", argNames: []);

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  AudioOutputDevice dco_decode_audio_output_device(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return AudioOutputDevice(
      id: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
      deviceClass: dco_decode_String(arr[2]),
      isCurrent: dco_decode_bool(arr[3]),
    );
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<AudioOutputDevice> dco_decode_list_audio_output_device(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_audio_output_device).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<Track> dco_decode_list_track(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_track).toList();
  }

  @protected
  PlaybackState dco_decode_playback_state(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 15)
      throw Exception('unexpected arr length: expect 15 but see ${arr.length}');
    return PlaybackState(
      playlist: dco_decode_list_track(arr[0]),
      currentIndex: dco_decode_i_32(arr[1]),
      currentUri: dco_decode_String(arr[2]),
      currentTitle: dco_decode_String(arr[3]),
      isPlaying: dco_decode_bool(arr[4]),
      positionMs: dco_decode_i_64(arr[5]),
      durationMs: dco_decode_i_64(arr[6]),
      volume: dco_decode_f_64(arr[7]),
      muted: dco_decode_bool(arr[8]),
      speed: dco_decode_f_64(arr[9]),
      shuffle: dco_decode_bool(arr[10]),
      repeatMode: dco_decode_repeat_mode(arr[11]),
      outputDeviceId: dco_decode_String(arr[12]),
      outputDeviceName: dco_decode_String(arr[13]),
      lastError: dco_decode_String(arr[14]),
    );
  }

  @protected
  RepeatMode dco_decode_repeat_mode(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return RepeatMode.values[raw as int];
  }

  @protected
  Track dco_decode_track(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return Track(
      uri: dco_decode_String(arr[0]),
      title: dco_decode_String(arr[1]),
    );
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  AudioOutputDevice sse_decode_audio_output_device(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_deviceClass = sse_decode_String(deserializer);
    var var_isCurrent = sse_decode_bool(deserializer);
    return AudioOutputDevice(
      id: var_id,
      name: var_name,
      deviceClass: var_deviceClass,
      isCurrent: var_isCurrent,
    );
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<AudioOutputDevice> sse_decode_list_audio_output_device(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <AudioOutputDevice>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_audio_output_device(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<Track> sse_decode_list_track(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Track>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_track(deserializer));
    }
    return ans_;
  }

  @protected
  PlaybackState sse_decode_playback_state(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_playlist = sse_decode_list_track(deserializer);
    var var_currentIndex = sse_decode_i_32(deserializer);
    var var_currentUri = sse_decode_String(deserializer);
    var var_currentTitle = sse_decode_String(deserializer);
    var var_isPlaying = sse_decode_bool(deserializer);
    var var_positionMs = sse_decode_i_64(deserializer);
    var var_durationMs = sse_decode_i_64(deserializer);
    var var_volume = sse_decode_f_64(deserializer);
    var var_muted = sse_decode_bool(deserializer);
    var var_speed = sse_decode_f_64(deserializer);
    var var_shuffle = sse_decode_bool(deserializer);
    var var_repeatMode = sse_decode_repeat_mode(deserializer);
    var var_outputDeviceId = sse_decode_String(deserializer);
    var var_outputDeviceName = sse_decode_String(deserializer);
    var var_lastError = sse_decode_String(deserializer);
    return PlaybackState(
      playlist: var_playlist,
      currentIndex: var_currentIndex,
      currentUri: var_currentUri,
      currentTitle: var_currentTitle,
      isPlaying: var_isPlaying,
      positionMs: var_positionMs,
      durationMs: var_durationMs,
      volume: var_volume,
      muted: var_muted,
      speed: var_speed,
      shuffle: var_shuffle,
      repeatMode: var_repeatMode,
      outputDeviceId: var_outputDeviceId,
      outputDeviceName: var_outputDeviceName,
      lastError: var_lastError,
    );
  }

  @protected
  RepeatMode sse_decode_repeat_mode(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return RepeatMode.values[inner];
  }

  @protected
  Track sse_decode_track(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_uri = sse_decode_String(deserializer);
    var var_title = sse_decode_String(deserializer);
    return Track(uri: var_uri, title: var_title);
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_audio_output_device(
    AudioOutputDevice self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.deviceClass, serializer);
    sse_encode_bool(self.isCurrent, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_audio_output_device(
    List<AudioOutputDevice> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_audio_output_device(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_track(List<Track> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_track(item, serializer);
    }
  }

  @protected
  void sse_encode_playback_state(PlaybackState self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_track(self.playlist, serializer);
    sse_encode_i_32(self.currentIndex, serializer);
    sse_encode_String(self.currentUri, serializer);
    sse_encode_String(self.currentTitle, serializer);
    sse_encode_bool(self.isPlaying, serializer);
    sse_encode_i_64(self.positionMs, serializer);
    sse_encode_i_64(self.durationMs, serializer);
    sse_encode_f_64(self.volume, serializer);
    sse_encode_bool(self.muted, serializer);
    sse_encode_f_64(self.speed, serializer);
    sse_encode_bool(self.shuffle, serializer);
    sse_encode_repeat_mode(self.repeatMode, serializer);
    sse_encode_String(self.outputDeviceId, serializer);
    sse_encode_String(self.outputDeviceName, serializer);
    sse_encode_String(self.lastError, serializer);
  }

  @protected
  void sse_encode_repeat_mode(RepeatMode self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_track(Track self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.uri, serializer);
    sse_encode_String(self.title, serializer);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }
}
