// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `apply_speed_after_seek`, `apply_volume`, `build_audio_sink`, `checked_index`, `clamp_speed`, `compute_next_index`, `configure_platform_gstreamer_runtime`, `create_device_sink`, `current_duration_ms`, `current_position_ms`, `current_track`, `device_id`, `ensure_runtime_started`, `ensure_runtime`, `fade_to`, `flutter_asset_to_uri`, `handle_command`, `input_to_uri`, `is_http_uri`, `join`, `list_output_devices`, `load_current`, `looks_like_uri`, `new`, `next_track`, `pause_playback`, `poll_bus`, `previous_track`, `recv_reply`, `refresh_output_devices`, `register_static_plugins`, `reset_buffering_for_uri`, `run_player_thread`, `runtime_slot`, `seek`, `send`, `set_output_device`, `set_speed`, `snapshot`, `start_playback`, `start`, `stop_fade`, `stop_pipeline`, `tick_fade`, `title_from_input`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `Command`, `FadeState`, `GStreamerPlayer`, `PlayerRuntime`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `clone`, `clone`, `clone`, `clone`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

Future<void> shutdownPlayer() =>
    RustLib.instance.api.crateApiPlayerShutdownPlayer();

Future<PlaybackState> setPlaylist({
  required List<String> inputs,
  required int startIndex,
}) => RustLib.instance.api.crateApiPlayerSetPlaylist(
  inputs: inputs,
  startIndex: startIndex,
);

Future<PlaybackState> play() => RustLib.instance.api.crateApiPlayerPlay();

Future<PlaybackState> playIndex({required int index}) =>
    RustLib.instance.api.crateApiPlayerPlayIndex(index: index);

Future<PlaybackState> pause() => RustLib.instance.api.crateApiPlayerPause();

Future<PlaybackState> togglePlayPause() =>
    RustLib.instance.api.crateApiPlayerTogglePlayPause();

Future<PlaybackState> stop() => RustLib.instance.api.crateApiPlayerStop();

Future<PlaybackState> previous() =>
    RustLib.instance.api.crateApiPlayerPrevious();

Future<PlaybackState> next() => RustLib.instance.api.crateApiPlayerNext();

Future<PlaybackState> seekMs({required PlatformInt64 positionMs}) =>
    RustLib.instance.api.crateApiPlayerSeekMs(positionMs: positionMs);

Future<PlaybackState> setVolume({required double volume}) =>
    RustLib.instance.api.crateApiPlayerSetVolume(volume: volume);

Future<PlaybackState> setMuted({required bool muted}) =>
    RustLib.instance.api.crateApiPlayerSetMuted(muted: muted);

Future<PlaybackState> fadeIn({required PlatformInt64 durationMs}) =>
    RustLib.instance.api.crateApiPlayerFadeIn(durationMs: durationMs);

Future<PlaybackState> fadeOut({required PlatformInt64 durationMs}) =>
    RustLib.instance.api.crateApiPlayerFadeOut(durationMs: durationMs);

Future<PlaybackState> setSpeed({required double speed}) =>
    RustLib.instance.api.crateApiPlayerSetSpeed(speed: speed);

Future<PlaybackState> setShuffle({required bool enabled}) =>
    RustLib.instance.api.crateApiPlayerSetShuffle(enabled: enabled);

Future<PlaybackState> setRepeatMode({required RepeatMode mode}) =>
    RustLib.instance.api.crateApiPlayerSetRepeatMode(mode: mode);

Future<PlaybackState> setOutputDevice({required String deviceId}) =>
    RustLib.instance.api.crateApiPlayerSetOutputDevice(deviceId: deviceId);

Future<List<AudioOutputDevice>> listOutputDevices() =>
    RustLib.instance.api.crateApiPlayerListOutputDevices();

Future<PlaybackState> getState() =>
    RustLib.instance.api.crateApiPlayerGetState();

class AudioOutputDevice {
  final String id;
  final String name;
  final String deviceClass;
  final bool isCurrent;

  const AudioOutputDevice({
    required this.id,
    required this.name,
    required this.deviceClass,
    required this.isCurrent,
  });

  @override
  int get hashCode =>
      id.hashCode ^ name.hashCode ^ deviceClass.hashCode ^ isCurrent.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AudioOutputDevice &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          deviceClass == other.deviceClass &&
          isCurrent == other.isCurrent;
}

class PlaybackState {
  final List<Track> playlist;
  final int currentIndex;
  final String currentUri;
  final String currentTitle;
  final bool isPlaying;
  final PlatformInt64 positionMs;
  final PlatformInt64 durationMs;
  final int bufferingPercent;
  final bool isBuffering;
  final double volume;
  final bool muted;
  final double speed;
  final bool shuffle;
  final RepeatMode repeatMode;
  final String outputDeviceId;
  final String outputDeviceName;
  final String lastError;

  const PlaybackState({
    required this.playlist,
    required this.currentIndex,
    required this.currentUri,
    required this.currentTitle,
    required this.isPlaying,
    required this.positionMs,
    required this.durationMs,
    required this.bufferingPercent,
    required this.isBuffering,
    required this.volume,
    required this.muted,
    required this.speed,
    required this.shuffle,
    required this.repeatMode,
    required this.outputDeviceId,
    required this.outputDeviceName,
    required this.lastError,
  });

  @override
  int get hashCode =>
      playlist.hashCode ^
      currentIndex.hashCode ^
      currentUri.hashCode ^
      currentTitle.hashCode ^
      isPlaying.hashCode ^
      positionMs.hashCode ^
      durationMs.hashCode ^
      bufferingPercent.hashCode ^
      isBuffering.hashCode ^
      volume.hashCode ^
      muted.hashCode ^
      speed.hashCode ^
      shuffle.hashCode ^
      repeatMode.hashCode ^
      outputDeviceId.hashCode ^
      outputDeviceName.hashCode ^
      lastError.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PlaybackState &&
          runtimeType == other.runtimeType &&
          playlist == other.playlist &&
          currentIndex == other.currentIndex &&
          currentUri == other.currentUri &&
          currentTitle == other.currentTitle &&
          isPlaying == other.isPlaying &&
          positionMs == other.positionMs &&
          durationMs == other.durationMs &&
          bufferingPercent == other.bufferingPercent &&
          isBuffering == other.isBuffering &&
          volume == other.volume &&
          muted == other.muted &&
          speed == other.speed &&
          shuffle == other.shuffle &&
          repeatMode == other.repeatMode &&
          outputDeviceId == other.outputDeviceId &&
          outputDeviceName == other.outputDeviceName &&
          lastError == other.lastError;
}

enum RepeatMode { none, one, all }

class Track {
  final String uri;
  final String title;

  const Track({required this.uri, required this.title});

  @override
  int get hashCode => uri.hashCode ^ title.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Track &&
          runtimeType == other.runtimeType &&
          uri == other.uri &&
          title == other.title;
}
