name: iOS Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ios-package:
    uses: ./.github/workflows/_ios-workflow.yml
    permissions:
      contents: read
    with:
      task: package
      artifact_name: gst-audio-flutter-ios-unsigned
    secrets: inherit
